version: '3.9'

services:
  app:
    container_name: medicine_schedule
    build: ./
    depends_on:
      - db
    command: sh -c 'until pg_isready -h db -p 5432; do sleep 1; done; alembic -c core/alembic.ini upgrade head && uvicorn core.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
  db:
    container_name: medicine_schedule_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-med_schedule_api}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASS:-12345678}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always